magic setup when kali chroot is missing

diff --git a/chroot_scripts/chrootboot b/chroot_scripts/chrootboot
--- a/chroot_scripts/chrootboot
+++ b/chroot_scripts/chrootboot
@@ -3,9 +3,26 @@
 
 export NEW_ROOT=/data/local/kali
 
+#chroot v0
 if [ -f /data/local/kali_img/kali.img ]; then
   export SOURCE_IMG=/data/local/kali_img/kali.img
   mount -o loop -t ext4 $SOURCE_IMG $NEW_ROOT
+fi
+
+#chroot v1
+if [ ! -d "${NEW_ROOT}" ]; then
+  if [ -r /data/local/kali_img/stockchroot.img ] && [ -x /system/bin/chroot_setup ] && [ -x /system/xbin/busybox ]; then
+    /system/bin/chroot_v1_setup
+    if [ "$?" != "0" ]; then
+      #chroot_v1_setup failed, remove broken install
+      busybox rm -rf "${NEW_ROOT}"
+      exit 1
+    fi
+  else
+    exit 1
+  fi
+else
+  exit 1
 fi
 
 # Mount other filesystems for chroot environment
